language: java
jdk:
  - openjdk11
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build

before_install:
  - sudo apt-get install jq

after_success:
  - bash <(curl -s https://codecov.io/bash)
