version: '3.7'
services:
  app:
    build:
      context: ./docker
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:mariadb://db:3306/field
      - DB_USER=root
      - DB_PASSWORD=root
      - HIBERNATE_DDL_AUTO=create
      - SHOW_SQL=false
  db:
      image: mariadb:latest
      volumes:
        - ~/local_db/:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=field
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
      ports:
        - 3306:3306
